### Reading Data From Different Sources

In [8]:
import pandas as pd
from io import StringIO
Data='{"employee_name":"James","email":"james@gmail.com","job_profile":[{"title1":"Team :Lead","title2":"Sr. Developer"}]}'
pd.read_json(StringIO(Data))

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team :Lead', 'title2': 'Sr. Develo..."

In [9]:
df

       employee_name            email    job_profile
title1         James  james@gmail.com      Team Lead
title2         James  james@gmail.com  Sr. Developer

In [ ]:
df.to_json()     #convert back to json

'{"employee_name":{"title1":"James","title2":"James"},"email":{"title1":"james@gmail.com","title2":"james@gmail.com"},"job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}'

In [11]:
df.to_json(orient='index')

'{"title1":{"employee_name":"James","email":"james@gmail.com","job_profile":"Team Lead"},"title2":{"employee_name":"James","email":"james@gmail.com","job_profile":"Sr. Developer"}}'

In [17]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":"Team Lead"},{"employee_name":"James","email":"james@gmail.com","job_profile":"Sr. Developer"}]'

In [41]:
import pandas as pd
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

url = "https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv"
df = pd.read_csv(url)

print(df.head())

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1081)>

In [38]:
pip install certifi

Collecting certifi
  Using cached certifi-2026.4.22-py3-none-any.whl.metadata (2.5 kB)
Using cached certifi-2026.4.22-py3-none-any.whl (135 kB)
Installing collected packages: certifi
Successfully installed certifi-2026.4.22

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.